baseURL = 'https://neuro-arg.github.io/'
languageCode = 'en-us'
title = 'Neuro ARG site'
theme = 'ananke'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "toolbox"
    name = "Toolbox"
    url = "/toolbox.html"
    weight = 15

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
